// Generated by CoffeeScript 1.7.1
(function() {
  var Seq;

  module.exports = Seq = (function() {
    function Seq(seq, name, id) {
      var meta;
      this.seq = seq;
      this.name = name;
      this.id = id;
      meta = {};
    }

    return Seq;

  })();

}).call(this);
