// Generated by CoffeeScript 1.7.1
var GenericReader, xhr;

xhr = require('nets');

module.exports = GenericReader = (function() {
  function GenericReader() {}

  GenericReader.read = function(url, callback) {
    var onret;
    onret = (function(_this) {
      return function(err, response, text) {
        return _this._onRetrieval(text, callback);
      };
    })(this);
    return xhr(url, onret);
  };

  GenericReader._onRetrieval = function(text, callback) {
    var end, rText, start;
    start = new Date().getTime();
    rText = this.parse(text);
    end = new Date().getTime();
    console.log("Parsing time: " + (end - start) + " ms");
    return callback(rText);
  };

  return GenericReader;

})();
