(function(v,w,x,y,z,A,B,C,D,E,F,G,H,I,K,L,M,N,O,P,Q,R,f,S,T,U,V,W,X,Y,Z,$,c,aa,ba,ca,da,ea,j,fa,k,n,p,ga,l,ha,s,ia,q,ja,r,t,u,ka,m){j("JSV.js2d");k(["JSV.popup.JSVGenericPopup"],"JSV.js2d.JsPopup",["JSV.popup.JSVPopupResourceBundle"],function(){c$=r(JSV.js2d,"JsPopup",JSV.popup.JSVGenericPopup);l(c$,function(){u(this,JSV.js2d.JsPopup,[])});c(c$,"jpiInitialize",function(a,b){var d=new JSV.popup.JSVPopupResourceBundle;this.initialize(a,d,b)},"javajs.api.PlatformViewer,~S");f(c$,"updateButton",function(a,
b,d){var h=[b];b=h[0];h=this.getEntryIcon(h);null!=h&&a.setIcon(h);null!=b&&a.setText(b);null!=d&&a.setActionCommand(d);this.thisPopup.tainted=!0},"~O,~S,~S");f(c$,"newMenuItem",function(a,b,d,h,e){this.updateButton(b,d,h);null!=e&&e.startsWith("Focus")&&(b.addMouseListener(this),e=a.getName()+"."+e);b.setName(null==e?a.getName()+".":e);this.menuAddItem(a,b);return b},"~O,~O,~S,~S,~S");c(c$,"menuAddButtonGroup",function(a){null==this.buttonGroup&&(this.buttonGroup=new Jmol.Menu.ButtonGroup(this.thisPopup));
this.buttonGroup.add(a)},"~O");c(c$,"menuAddItem",function(a,b){a.add(b);this.thisPopup.tainted=!0},"~O,~O");c(c$,"menuAddSeparator",function(a){a.add(new Jmol.Menu.MenuItem(this.thisPopup,null,!1,!1));this.thisPopup.tainted=!0},"~O");c(c$,"menuAddSubMenu",function(a,b){this.menuAddItem(a,b)},"~O,~O");c(c$,"menuClearListeners",function(a){a.dispose()},"~O");c(c$,"menuCreateCheckboxItem",function(a,b,d,h,e,g){var c=null,c=new Jmol.Menu.MenuItem(this.thisPopup,b,!g,g);c.setSelected(e);c.addItemListener(this);
return this.newMenuItem(a,c,b,d,h)},"~O,~S,~S,~S,~B,~B");c(c$,"menuCreateItem",function(a,b,d,h){var e=null,e=new Jmol.Menu.MenuItem(this.thisPopup,b);e.addActionListener(this);return this.newMenuItem(a,e,b,d,h)},"~O,~S,~S,~S");c(c$,"menuCreatePopup",function(a){return new Jmol.Menu.PopupMenu(this.viewer.applet,a)},"~S");c(c$,"menuEnable",function(a,b){if(a.isItem)this.menuEnableItem(a,b);else{try{a.setEnabled(b)}catch(d){}this.thisPopup.tainted=!0}},"~O,~B");c(c$,"menuEnableItem",function(a,b){try{a.setEnabled(b)}catch(d){}this.thisPopup.tainted=
!0},"~O,~B");c(c$,"menuGetAsText",function(a,b,d,h){d=d.getComponents();for(var e=0;e<d.length;e++){var g=d[e],c=null;if(g.isMenu)h=g.getName(),c="enabled:"+g.isEnabled(),this.addItemText(a,"M",b,h,g.getText(),null,c),this.menuGetAsText(a,b+1,g.getPopupMenu(),h);else if(g.isItem){c="enabled:"+g.isEnabled();g.isCheckBox&&(c+=";checked:"+g.getState());var f=this.fixScript(g.getName(),g.getActionCommand());this.addItemText(a,"I",b,g.getName(),g.getText(),f,c)}else this.addItemText(a,"S",b,h,null,null,
null)}},"JU.SB,~N,~O,~S");c(c$,"menuGetId",function(a){return a.getName()},"~O");c(c$,"menuGetItemCount",function(a){return a.getItemCount()},"~O");c(c$,"menuGetParent",function(a){return a.getParent()},"~O");c(c$,"menuGetPosition",function(a){var b=menuGetParent(a);if(null!=b)for(var d=b.getItemCount();0<=--d;)if(b.getItem(d)==a)return;d;return-1},"~O");c(c$,"menuInsertSubMenu",function(){},"~O,~O,~N");c(c$,"menuNewSubMenu",function(a,b){var d=new Jmol.Menu.SubMenu(this.thisPopup,a);this.updateButton(d,
a,null);d.setName(b);d.setAutoscrolls(!0);return d},"~S,~S");c(c$,"menuRemoveAll",function(a,b){a.removeAll(b);this.thisPopup.tainted=!0},"~O,~N");c(c$,"menuSetAutoscrolls",function(a){a.setAutoscrolls(!0);this.thisPopup.tainted=!0},"~O");c(c$,"menuSetCheckBoxState",function(a,b){a.setSelected(b);this.thisPopup.tainted=!0},"~O,~B");c(c$,"menuSetCheckBoxOption",function(){return null},"~O,~S,~S");c(c$,"menuSetCheckBoxValue",function(a){this.setCheckBoxValue(a,a.getActionCommand(),a.isSelected());this.thisPopup&&
(this.thisPopup.tainted=!0)},"~O");c(c$,"menuSetLabel",function(a,b){a.setText(b);this.thisPopup.tainted=!0},"~O,~S");c(c$,"menuSetListeners",function(){});c(c$,"menuShowPopup",function(a,b,d){a.menuShowPopup(b,d)},"~O,~N,~N");c(c$,"updateSpecialMenuItem",function(a){a.setText(this.getSpecialLabel(a.getName(),a.getText()))},"~O");c(c$,"menuIsEnabled",function(a){return a.isEnabled()},"~O")});j("JSV.popup");k(["JSV.api.JSVAbstractMenu","$.JSVPopupMenu","java.util.Hashtable","$.Properties","JU.List"],
"JSV.popup.JSVGenericPopup","java.util.StringTokenizer JU.PT $.SB JSV.common.Annotation $.JSVersion JSV.popup.JSVPopupResourceBundle J.util.Logger".split(" "),function(){c$=p(function(){this.strMenuStructure=this.currentMenuItemId=this.buttonGroup=this.menuText=this.htCheckbox=this.viewer=null;this.updateMode=0;this.AppletOnly=this.SignedOnly=this.htMenus=this.thisPopup=this.popupMenu=this.menuName=null;this.isSigned=this.isApplet=this.isJS=this.allowSignedFeatures=!1;this.hnmrPeaks=this.cnmrPeaks=
null;this.aboutComputedMenuBaseCount=0;this.pd=null;this.thisY=this.thisX=0;this.thisJsvp=null;n(this,arguments)},JSV.popup,"JSVGenericPopup",null,[JSV.api.JSVPopupMenu,JSV.api.JSVAbstractMenu]);t(c$,function(){this.htCheckbox=new java.util.Hashtable;this.menuText=new java.util.Properties;this.htMenus=new java.util.Hashtable;this.SignedOnly=new JU.List;this.AppletOnly=new JU.List});l(c$,function(){});f(c$,"initialize",function(a,b,d){this.viewer=a;this.menuName=d;this.thisPopup=this.popupMenu=this.menuCreatePopup(d);
this.menuSetListeners();this.htMenus.put(d,this.popupMenu);this.isJS=a.isJS;this.allowSignedFeatures=!a.isApplet||a.isSigned;this.addMenuItems("",d,this.popupMenu,b);try{this.jpiUpdateComputedMenus()}catch(h){if(s(h,NullPointerException))System.out.println("JSVGenericPopup error "+h);else throw h;}},"JSV.common.JSViewer,JSV.popup.PopupResource,~S");c(c$,"jpiDispose",function(){this.menuClearListeners(this.popupMenu);this.popupMenu=this.thisPopup=null});c(c$,"jpiGetMenuAsObject",function(){return this.popupMenu});
c(c$,"jpiGetMenuAsString",function(a){this.updateForShow();var b=a.indexOf("|");if(0<=b){var d=a.substring(b);a=a.substring(0,b);if(0<=d.indexOf("current"))return a=new JU.SB,b=this.htMenus.get(this.menuName),this.menuGetAsText(a,0,b,"PopupMenu"),a.toString()}return(new JSV.popup.JSVPopupResourceBundle).getMenuAsText(a)},"~S");c(c$,"jpiShow",function(a,b){this.show(a,b,!1);this.restorePopupMenu();this.menuShowPopup(this.popupMenu,this.thisX,this.thisY)},"~N,~N");c(c$,"jpiUpdateComputedMenus",function(){-1!=
this.updateMode&&(this.updateMode=0,this.getViewerData(),this.updateFileMenu(),this.updateFileTypeDependentMenus(),this.updateMode=1,this.updateAboutSubmenu())});f(c$,"getEntryIcon",function(a){var b=a[0];if(!b.startsWith("<"))return null;var d=b.indexOf(">");a[0]=b.substring(d+1);a=b.substring(1,d);return this.getImageIcon(a)},"~A");f(c$,"getImageIcon",function(){return null},"~S");f(c$,"checkBoxStateChanged",function(a){this.restorePopupMenu();this.menuSetCheckBoxValue(a);a=this.menuGetId(a);null!=
a&&(this.currentMenuItemId=a)},"~O");c$.addItemText=f(c$,"addItemText",function(a,b,d,h,e,c,f){a.appendC(b).appendI(d).appendC("\t").append(h);null==e?a.append(".\n"):a.append("\t").append(e).append("\t").append(null==c||0==c.length?"-":c).append("\t").append(f).append("\n")},"JU.SB,~S,~N,~S,~S,~S,~S");f(c$,"fixScript",function(a,b){return b},"~S,~S");f(c$,"restorePopupMenu",function(){this.thisPopup=this.popupMenu});f(c$,"setCheckBoxValue",function(a,b,d){this.checkForCheckBoxScript(a,b,d)},"~O,~S,~B");
f(c$,"getViewerData",function(){this.isApplet=this.viewer.isApplet;this.isSigned=this.viewer.isSigned});f(c$,"updateFileTypeDependentMenus",function(){for(var a=this.SignedOnly.size();0<=--a;)this.menuEnable(this.SignedOnly.get(a),this.isSigned||!this.isApplet);for(a=this.AppletOnly.size();0<=--a;)this.menuEnable(this.AppletOnly.get(a),this.isApplet)});f(c$,"addMenuItems",function(a,b,d,c){a=a+"."+b;var e=c.getStructure(b);J.util.Logger.debugging&&J.util.Logger.debug(a+" --- "+e);if(null==e)this.menuCreateItem(d,
"#"+b,"","");else{b=new java.util.StringTokenizer(e);for(var g;0<=e.indexOf("@");){for(e="";b.hasMoreTokens();)e+=" "+((g=b.nextToken()).startsWith("@")?c.getStructure(g):g);e=e.substring(1);b=new java.util.StringTokenizer(e)}for(;b.hasMoreTokens();)if(g=b.nextToken(),this.checkKey(g)){var e=c.getWord(g),f=null,f="",j=!1,e=this.fixLabel(null==e?g:e);if(!e.equals("null")){if(0<=g.indexOf("Menu"))0>g.indexOf("more")&&(this.buttonGroup=null),e=this.menuNewSubMenu(e,a+"."+g),this.menuAddSubMenu(d,e),
this.htMenus.put(g,e),0>g.indexOf("Computed")&&this.addMenuItems(a,g,e,c),f=e;else if("-".equals(g)){this.menuAddSeparator(d);continue}else if(g.contains("CB")||g.contains("RD")){var j=!0,f=c.getStructure(g),k=e,j=j&&g.contains("RD"),f=this.menuCreateCheckboxItem(d,e,k+":"+f,a+"."+g,!1,j);this.rememberCheckbox(k,f);j&&this.menuAddButtonGroup(f)}else{f=c.getStructure(g);null==f&&(f=g);if(!this.isJS&&g.contains("JS"))continue;f=this.menuCreateItem(d,e,f,a+"."+g)}!this.allowSignedFeatures&&g.contains("SIGNED")&&
this.menuEnable(f,!1);g.startsWith("SIGNED")&&this.SignedOnly.addLast(f);this.htMenus.put(g,f)}}}},"~S,~S,~O,JSV.popup.PopupResource");f(c$,"fixLabel",function(a){a.startsWith("_")?a=a.substring(a.indexOf("_",2)+1):a.equals("VERSION")&&(a=JSV.common.JSVersion.VERSION);a=JU.PT.simpleReplace(a,"CB","");a=JU.PT.simpleReplace(a,"Menu","");return a=JU.PT.simpleReplace(a,"_"," ")},"~S");f(c$,"checkKey",function(a){return 0>a.indexOf("JAVA")&&!(a.indexOf("NOGL")&&this.viewer.isWebGL)},"~S");f(c$,"rememberCheckbox",
function(a,b){this.htCheckbox.put(a+"::"+this.htCheckbox.size(),b)},"~S,~O");f(c$,"checkForCheckBoxScript",function(a,b,d){if(this.menuIsEnabled(a)){if(0>b.indexOf("##")){var c=b.indexOf(":");if(0>c){J.util.Logger.error("check box "+a+" IS "+b);return}var e=b.substring(0,c);if(e.endsWith("P!"))if(0<=e.indexOf("??"))b=this.menuSetCheckBoxOption(a,e,b);else{if(!d)return;b="set picking "+e.substring(0,e.length-2)}else{b=b.substring(c+1);if(0<=(c=b.indexOf("|")))b=(d?b.substring(0,c):b.substring(c+1)).trim();
b=JU.PT.simpleReplace(b,"T/F",d?" TRUE":" FALSE")}}this.viewer.runScript(b)}},"~O,~S,~B");c(c$,"checkMenuClick",function(a,b){this.checkMenuClickGP(a,b)},"~O,~S");f(c$,"checkMenuClickGP",function(a,b){this.restorePopupMenu();if(!(null==b||0==b.length)){var d=this.menuGetId(a);null!=d&&(b=this.fixScript(d,b),this.currentMenuItemId=d);this.viewer.runScript(b)}},"~O,~S");f(c$,"updateFileMenu",function(){this.htMenus.get("fileMenu")});f(c$,"updateSpectraMenu",function(){var a=this.htMenus.get("hnmrMenu"),
b=this.htMenus.get("cnmrMenu");null!=a&&this.menuRemoveAll(a,0);null!=b&&this.menuRemoveAll(b,0);var d=this.htMenus.get("spectraMenu");if(null!=d){this.menuRemoveAll(d,0);var c=(new Boolean(this.setSpectraMenu(a,this.hnmrPeaks)|this.setSpectraMenu(b,this.cnmrPeaks))).valueOf();c&&(null!=a&&this.menuAddSubMenu(d,a),null!=b&&this.menuAddSubMenu(d,b));this.menuEnable(d,c)}});f(c$,"setSpectraMenu",function(a,b){if(null==a)return!1;this.menuEnable(a,!1);var d=null==b?0:b.size();if(0==d)return!1;for(var c=
0;c<d;c++){var e=b.get(c),f=JU.PT.getQuotedAttribute(e,"title"),e=JU.PT.getQuotedAttribute(e,"atoms");null!=e&&this.menuCreateItem(a,f,"select visible & (@"+JU.PT.simpleReplace(e,","," or @")+")","Focus"+c)}this.menuEnable(a,!0);return!0},"~O,JU.List");f(c$,"updateAboutSubmenu",function(){var a=this.htMenus.get("aboutComputedMenu");null!=a&&this.menuRemoveAll(a,this.aboutComputedMenuBaseCount)});f(c$,"updateForShow",function(){-1!=this.updateMode&&(this.getViewerData(),this.updateMode=2,this.updateSpectraMenu(),
this.updateAboutSubmenu())});f(c$,"show",function(a,b,d){this.thisJsvp=this.viewer.selectedPanel;this.setEnables(this.thisJsvp);-2147483648!=a&&(this.thisX=a,this.thisY=b);this.updateForShow();d&&this.menuShowPopup(this.popupMenu,this.thisX,this.thisY)},"~N,~N,~B");f(c$,"checkMenuFocus",function(a,b,d){0>a.indexOf("Focus")||d&&this.viewer.runScript(b)},"~S,~S,~B");c(c$,"getSelected",function(){return!1},"~S");c(c$,"setCompoundMenu",function(){},"JU.List,~B");c(c$,"setEnabled",function(a,b){a||(this.setItemEnabled("_SIGNED_FileMenu",
!1),this.setItemEnabled("ViewMenu",!1),this.setItemEnabled("Views",!1),this.setItemEnabled("Script",!1),this.setItemEnabled("Print",!1));this.setItemEnabled("ZoomMenu",b)},"~B,~B");f(c$,"setEnables",function(a){this.pd=a.getPanelData();a=this.pd.getSpectrum();var b=this.pd.isShowAllStacked(),d=this.pd.haveSelectedSpectrum();this.setItemEnabled("Integration",this.pd.getSpectrum().canIntegrate());this.setItemEnabled("Measurements",this.pd.hasCurrentMeasurements(JSV.common.Annotation.AType.Measurements));
this.setItemEnabled("Peaks",this.pd.getSpectrum().is1D());this.setItemEnabled("Predicted_Solution_Colour",d&&a.canShowSolutionColor());this.setItemEnabled("Toggle_Trans/Abs",d&&a.canConvertTransAbs());this.setItemEnabled("Show_Overlay_Key",b&&1==this.pd.getNumberOfGraphSets());this.setItemEnabled("Overlay_Offset...",b);this.setItemEnabled("JDXMenu",a.canSaveAsJDX());this.setItemEnabled("ExportAsMenu",!0)},"JSV.api.JSVPanel");f(c$,"setItemEnabled",function(a,b){var d=this.htMenus.get(a);null!=d&&this.menuEnable(d,
b)},"~S,~B");c(c$,"setSelected",function(a,b){var d=this.htMenus.get(a);null!=d&&(this.menuEnable(d,!1),this.menuSetCheckBoxState(d,b),this.menuEnable(d,!0))},"~S,~B");q(c$,"dumpList",!1,"UPDATE_NEVER",-1,"UPDATE_ALL",0,"UPDATE_CONFIG",1,"UPDATE_SHOW",2)});j("JSV.api");m(JSV.api,"JSVAbstractMenu");j("JSV.api");k(["javajs.api.GenericMenuInterface"],"JSV.api.JSVPopupMenu",null,function(){m(JSV.api,"JSVPopupMenu",javajs.api.GenericMenuInterface)});j("javajs.api");m(javajs.api,"GenericMenuInterface");
j("JSV.popup");k(["JSV.popup.PopupResource"],"JSV.popup.JSVPopupResourceBundle",["JU.SB"],function(){c$=r(JSV.popup,"JSVPopupResourceBundle",JSV.popup.PopupResource);c(c$,"getMenuName",function(){return"appMenu"});c(c$,"buildStructure",function(){this.addItems(JSV.popup.JSVPopupResourceBundle.menuContents);this.addItems(JSV.popup.JSVPopupResourceBundle.structureContents)});c(c$,"getWordContents",function(){return[]});c(c$,"getMenuAsText",function(a){return"# Jmol.mnu "+a+"\n\n# Part I -- Menu Structure\n# ------------------------\n\n"+
this.dumpStructure(JSV.popup.JSVPopupResourceBundle.menuContents)+"\n\n# Part II -- Key Definitions\n# --------------------------\n\n"+this.dumpStructure(JSV.popup.JSVPopupResourceBundle.structureContents)+"\n\n# Part III -- Word Translations\n# -----------------------------\n\n"+this.dumpWords()},"~S");f(c$,"dumpWords",function(){for(var a=this.getWordContents(),b=new JU.SB,d=0;d<a.length;d++){var c=a[d++];null==this.structure.getProperty(c)&&b.append(c).append(" | ").append(a[d]).appendC("\n")}return b.toString()});
f(c$,"dumpStructure",function(a){for(var b="",d=new JU.SB,c=0;c<a.length;c++){var e=a[c][0],f=this.words.getProperty(e);null!=f&&(e+=" | "+f);d.append(e).append(" = ").append(null==a[c][1]?b:b=a[c][1]).appendC("\n")}return d.toString()},"~A");q(c$,"menuContents",[["appMenu","Toggle_Grid Toggle_X_Axis Toggle_Y_Axis Toggle_Coordinates Reverse_Plot - Next_View Previous_View Clear_Views Reset_View Set_Zoom... - Views... Overlay_Offset... Script... - Properties"],["appletMenu","_SIGNED_FileMenu ViewMenu ZoomMenu Views... Overlay_Offset... - Measurements Peaks Integration Toggle_Trans/Abs Predicted_Solution_Colour - Script... - Print... - AboutMenu"],
["_SIGNED_FileMenu","SaveAsMenu ExportAsMenu"],["SaveAsMenu","Original... JDXMenu CML XML(AnIML)"],["JDXMenu","XY DIF DIFDUP FIX PAC SQZ"],["ExportAsMenu","JPG PNG SVG PDF"],["ViewMenu","Toggle_Grid Toggle_X_Axis Toggle_Y_Axis Toggle_Coordinates Reverse_Plot Show_Header... Show_Overlay_Key... Window"],["ZoomMenu","Next_View Previous_View Reset_View Clear_Views Set_Zoom..."],["AboutMenu","VERSION"]],"structureContents",[["Show_Header...","showProperties"],["Window","window"],["Show_Overlay_Key...",
"showKey"],["Next_View","zoom next;showMenu"],["Previous_View","zoom prev;showMenu"],["Clear_Views","zoom clear"],["Reset_View","zoom out"],["Views...","view"],["Overlay_Offset...","stackOffsetY"],["Script...","script INLINE"],["Set_Zoom...","zoom"],["Properties","showProperties"],["Toggle_X_Axis","XSCALEON toggle;showMenu"],["Toggle_Y_Axis","YSCALEON toggle;showMenu"],["Toggle_Grid","GRIDON toggle;showMenu"],["Toggle_Coordinates","COORDINATESON toggle;showMenu"],["Reverse_Plot","REVERSEPLOT toggle;showMenu"],
["Measurements","SHOWMEASUREMENTS"],["Peaks","SHOWPEAKLIST"],["Integration","SHOWINTEGRATION"],["Toggle_Trans/Abs","IRMODE TOGGLE"],["Predicted_Solution_Colour","GETSOLUTIONCOLOR"],["Print...","print"],["Original...","write SOURCE"],["CML","write CML"],["XML(AnIML)","write XML"],["XY","write XY"],["DIF","write DIF"],["DIFDUP","write DIFDUP"],["FIX","write FIX"],["PAC","write PAC"],["SQZ","write SQZ"],["JPG","write JPG"],["SVG","write SVG"],["PNG","write PNG"],["PDF","write PDF"]])});j("JSV.popup");
k(null,"JSV.popup.PopupResource",["java.util.Properties"],function(){c$=p(function(){this.words=this.structure=null;n(this,arguments)},JSV.popup,"PopupResource");l(c$,function(){this.structure=new java.util.Properties;this.words=new java.util.Properties;this.buildStructure()});f(c$,"getMenuAsText",function(){return null},"~S");f(c$,"getStructure",function(a){return this.structure.getProperty(a)},"~S");f(c$,"getWord",function(a){var b=this.words.getProperty(a);return null==b?a:b},"~S");f(c$,"addItems",
function(a){for(var b="",d=0;d<a.length;d++){var c=a[d][1];null==c&&(c=b);b=c;this.structure.setProperty(a[d][0],c)}},"~A")})})(Clazz,Clazz.newArray,Clazz.newBooleanArray,Clazz.newByteArray,Clazz.newCharArray,Clazz.newDoubleArray,Clazz.newFloatArray,Clazz.newIntArray,Clazz.newLongArray,Clazz.newShortArray,Clazz.prepareCallback,Clazz.decorateAsClass,Clazz.isClassDefined,Clazz.defineEnumConstant,Clazz.cloneFinals,Clazz.inheritArgs,Clazz.pu$h,Clazz.declareInterface,Clazz.declarePackage,Clazz.makeConstructor,
Clazz.overrideConstructor,Clazz.load,Clazz.defineMethod,Clazz.innerTypeInstance,Clazz.instanceOf,Clazz.p0p,Clazz.makeFunction,Clazz.superConstructor,Clazz.defineStatics,Clazz.registerSerializableFields,Clazz.declareType,Clazz.superCall,Clazz.overrideMethod,Clazz.declareAnonymous,Clazz.checkPrivateMethod,Clazz.prepareFields,Clazz.instantialize,Clazz.doubleToInt,Clazz.declarePackage,Clazz.instanceOf,Clazz.load,Clazz.instantialize,Clazz.decorateAsClass,Clazz.floatToInt,Clazz.makeConstructor,Clazz.defineEnumConstant,
Clazz.exceptionOf,Clazz.newIntArray,Clazz.defineStatics,Clazz.newFloatArray,Clazz.declareType,Clazz.prepareFields,Clazz.superConstructor,Clazz.newByteArray,Clazz.declareInterface,Clazz.p0p,Clazz.pu$h,Clazz.newShortArray,Clazz.innerTypeInstance,Clazz.isClassDefined,Clazz.prepareCallback,Clazz.newArray,Clazz.castNullAs,Clazz.floatToShort,Clazz.superCall,Clazz.decorateAsType,Clazz.newBooleanArray,Clazz.newCharArray,Clazz.implementOf,Clazz.newDoubleArray,Clazz.overrideConstructor,Clazz.supportsNativeObject,
Clazz.extendedObjectMethods,Clazz.callingStackTraces,Clazz.clone,Clazz.doubleToShort,Clazz.innerFunctions,Clazz.getInheritedLevel,Clazz.getParamsType,Clazz.isAF,Clazz.isAI,Clazz.isAS,Clazz.isASS,Clazz.isAP,Clazz.isAFloat,Clazz.isAII,Clazz.isAFF,Clazz.isAFFF,Clazz.tryToSearchAndExecute,Clazz.getStackTrace,Clazz.inheritArgs);
